function randomData() {
    return Math.round(Math.random()*500);
}



$(function () {
    var geoCoordMap={};
    for(var i=0;i<city.length;i++){
        for(var j=0;j<city[i].children.length; j++){
            // console.log(city[i].children[j].name);
            geoCoordMap[city[i].children[j].name] = [parseFloat(city[i].children[j].log),parseFloat(city[i].children[j].lat)]
        }
    }
    // console.log(cityData.length);
    // var geoCoordMap = {
    //     '黑龙江': [127.9688, 45.368],
    //     '内蒙古': [110.3467, 41.4899],
    //     "吉林": [125.8154, 44.2584],
    //     '北京市': [116.4551, 40.2539],
    //     "辽宁": [123.1238, 42.1216],
    //     "河北": [114.4995, 38.1006],
    //     "天津": [117.4219, 39.4189],
    //     "山西": [112.3352, 37.9413],
    //     "陕西": [109.1162, 34.2004],
    //     "甘肃": [103.5901, 36.3043],
    //     "宁夏": [106.3586, 38.1775],
    //     "青海": [101.4038, 36.8207],
    //     "新疆": [87.9236, 43.5883],
    //     "西藏": [91.11, 29.97],
    //     "四川": [103.9526, 30.7617],
    //     "重庆": [108.384366, 30.439702],
    //     "山东": [117.1582, 36.8701],
    //     "河南": [113.4668, 34.6234],
    //     "江苏": [118.8062, 31.9208],
    //     "安徽": [117.29, 32.0581],
    //     "湖北": [114.3896, 30.6628],
    //     "浙江": [119.5313, 29.8773],
    //     "福建": [119.4543, 25.9222],
    //     "江西": [116.0046, 28.6633],
    //     "湖南": [113.0823, 28.2568],
    //     "贵州": [106.6992, 26.7682],
    //     "云南": [102.9199, 25.4663],
    //     "广东": [113.12244, 23.009505],
    //     "广西": [108.479, 23.1152],
    //     "海南": [110.3893, 19.8516],
    //     '上海': [121.4648, 31.2891],
    // };

    var convertData = function (data) {
        var res = [];
        for (var i = 0; i < data.length; i++) {
            var geoCoord = geoCoordMap[data[i].name];
            if (geoCoord) {
                res.push(geoCoord.concat(data[i].value*50));
            }
        }
        return res;
    };

    // var mydata = convertData([
    //     {name: '北京',value: '100' },{name: '天津',value: randomData() },
    //     {name: '上海',value: randomData() },{name: '重庆',value: randomData() },
    //     {name: '河北',value: randomData() },{name: '河南',value: randomData() },
    //     {name: '云南',value: randomData() },{name: '辽宁',value: randomData() },
    //     {name: '黑龙江',value: randomData() },{name: '湖南',value: randomData() },
    //     {name: '安徽',value: randomData() },{name: '山东',value: randomData() },
    //     {name: '新疆',value: randomData() },{name: '江苏',value: randomData() },
    //     {name: '浙江',value: randomData() },{name: '江西',value: randomData() },
    //     {name: '湖北',value: randomData() },{name: '广西',value: randomData() },
    //     {name: '甘肃',value: randomData() },{name: '山西',value: randomData() },
    //     {name: '内蒙古',value: randomData() },{name: '陕西',value: randomData() },
    //     {name: '吉林',value: randomData() },{name: '福建',value: randomData() },
    //     {name: '贵州',value: randomData() },{name: '广东',value: randomData() },
    //     {name: '青海',value: randomData() },{name: '西藏',value: randomData() },
    //     {name: '四川',value: randomData() },{name: '宁夏',value: randomData() },
    //     {name: '海南',value: randomData() },{name: '台湾',value: randomData() },
    //     {name: '香港',value: randomData() },{name: '澳门',value: randomData() }
    // ]);

    // var mydata = convertData([
    //     {name: "天水", value: 999},
    //     {name: "河池", value: 654},
    //     {name: "桂林", value: 546},
    //     {name: "南宁", value: 545},
    //     {name: "柳州", value: 564},
    //     {name: "崇左", value: 654},
    //     {name: "来宾", value: 87},
    //     {name: "玉林", value: 99},
    //     {name: "梧州", value: 55},
    //     {name: "贺州", value: 767},
    //     {name: "钦州", value: 567},
    //     {name: "贵港", value: 55},
    //     {name: "防城港", value: 43},
    //     {name: "北海", value: 234},
    //     // {name: "七七哈尔"}
    // ]);
    // console.log(mydata)
    var mydata = convertData(
        [{'name': '遂宁', 'value': 11},
            {'name': '成都', 'value': 407},
            {'name': '福州', 'value': 76},
            {'name': '武汉', 'value': 217},
            {'name': '长沙', 'value': 127},
            {'name': '哈尔滨', 'value': 51},
            {'name': '南京', 'value': 186},
            {'name': '烟台', 'value': 28},
            {'name': '黄冈', 'value': 11},
            {'name': '秦皇岛', 'value': 20},
            {'name': '肇庆', 'value': 11},
            {'name': '贵阳', 'value': 36},
            {'name': '宜春', 'value': 13},
            {'name': '荆州', 'value': 18},
            {'name': '南宁', 'value': 59},
            {'name': '济南', 'value': 87},
            {'name': '泰安', 'value': 16},
            {'name': '莱芜', 'value': 7},
            {'name': '昌吉', 'value': 1},
            {'name': '齐齐哈尔', 'value': 5},
            {'name': '忻州', 'value': 5},
            {'name': '邵阳', 'value': 11},
            {'name': '丹东', 'value': 4},
            {'name': '攀枝花', 'value': 6},
            {'name': '无锡', 'value': 41},
            {'name': '内江', 'value': 15},
            {'name': '郑州', 'value': 107},
            {'name': '淮南', 'value': 11},
            {'name': '唐山', 'value': 19},
            {'name': '鹤壁', 'value': 5},
            {'name': '昆明', 'value': 33},
            {'name': '襄阳', 'value': 11},
            {'name': '榆林', 'value': 7},
            {'name': '莆田', 'value': 10},
            {'name': '达州', 'value': 18},
            {'name': '临汾', 'value': 8},
            {'name': '张家界', 'value': 3},
            {'name': '安阳', 'value': 9},
            {'name': '海口', 'value': 22},
            {'name': '南通', 'value': 21},
            {'name': '宣城', 'value': 8},
            {'name': '吕梁', 'value': 5},
            {'name': '马鞍山', 'value': 12},
            {'name': '嘉兴', 'value': 27},
            {'name': '德州', 'value': 5},
            {'name': '吉林', 'value': 10},
            {'name': '邯郸', 'value': 20},
            {'name': '佳木斯', 'value': 2},
            {'name': '滁州', 'value': 15},
            {'name': '蚌埠', 'value': 15},
            {'name': '三明', 'value': 9},
            {'name': '东莞', 'value': 47},
            {'name': '玉溪', 'value': 9},
            {'name': '枣庄', 'value': 7},
            {'name': '晋中', 'value': 4},
            {'name': '珠海', 'value': 23},
            {'name': '临沂', 'value': 24},
            {'name': ' 池州', 'value': 2},
            {'name': '威海', 'value': 20},
            {'name': '连云港', 'value': 17},
            {'name': '盐城', 'value': 16},
            {'name': '宝鸡', 'value': 10},
            {'name': '孝感', 'value': 6},
            {'name': '清远', 'value': 11},
            {'name': '漯河', 'value': 10},
            {'name': '周口', 'value': 13},
            {'name': '长治', 'value': 9},
            {'name': '聊城', 'value': 9},
            {'name': '渭南', 'value': 8},
            {'name': '白山', 'value': 3},
            {'name': '安庆', 'value': 15},
            {'name': '鄂尔多斯', 'value': 5},
            {'name': '舟山', 'value': 5},
            {'name': '邢台', 'value': 9},
            {'name': '中山', 'value': 13},
            {'name': '松原', 'value': 4},
            {'name': '海东', 'value': 3},
            {'name': '萍乡', 'value': 4},
            {'name': '绍兴', 'value': 22},
            {'name': '东营', 'value': 12},
            {'name': '商洛', 'value': 4},
            {'name': '其他', 'value': 5},
            {'name': '伊犁', 'value': 6},
            {'name': '乌鲁木齐', 'value': 17},
            {'name': '鸡西', 'value': 2},
            {'name': '资阳', 'value': 5},
            {'name': '信 阳', 'value': 12},
            {'name': '乌海', 'value': 2},
            {'name': '汕尾', 'value': 8},
            {'name': '茂名', 'value': 14},
            {'name': '梅州', 'value': 10},
            {'name': '亳州', 'value': 5},
            {'name': '天门', 'value': 2},
            {'name': '铜陵', 'value': 8},
            {'name': '陇南', 'value': 3},
            {'name': '荆门', 'value': 10},
            {'name': '林芝', 'value': 1},
            {'name': '铁岭', 'value': 4},
            {'name': '惠州', 'value': 16},
            {'name': '滨州', 'value': 6},
            {'name': '贵港', 'value': 6},
            {'name': '许昌', 'value': 11},
            {'name': '鹰潭', 'value': 3},
            {'name': '衢州', 'value': 9},
            {'name': '遵义', 'value': 11},
            {'name': '黔东南', 'value': 4},
            {'name': ' 河源', 'value': 4},
            {'name': '揭阳', 'value': 8},
            {'name': '中卫', 'value': 1},
            {'name': '防城港', 'value': 1},
            {'name': '广元', 'value': 7},
            {'name': '西宁', 'value': 4},
            {'name': '承德', 'value': 5},
            {'name': '常德', 'value': 5},
            {'name': '安顺', 'value': 5},
            {'name': '海西', 'value': 1},
            {'name': '衡水', 'value': 4},
            {'name': '株洲', 'value': 9},
            {'name': '朝阳', 'value': 5},
            {'name': '阿拉善盟', 'value': 1},
            {'name': '其他', 'value': 2},
            {'name': '沧州', 'value': 10},
            {'name': '拉萨', 'value': 3},
            {'name': '钦州', 'value': 4},
            {'name': '阿勒泰', 'value': 2},
            {'name': '定西', 'value': 2},
            {'name': '恩施', 'value': 3},
            {'name': '黑河', 'value': 2},
            {'name': '乌兰察布', 'value': 2},
            {'name': '随州', 'value': 2},
            {'name': '锡林郭勒盟', 'value': 4},
            {'name': '喀什', 'value': 2},
            {'name': '阿里', 'value': 1},
            {'name': '阿克苏', 'value': 1},
            {'name': '阜新', 'value': 4},
            {'name': '鄂州', 'value': 2},
            {'name': '雅安', 'value': 1},
            {'name': '商丘', 'value': 8},
            {'name': '日喀则', 'value': 2},
            {'name': '那曲', 'value': 1},
            {'name': '北海', 'value': 4},
            {'name': '克孜勒苏', 'value': 2},
            {'name': '辽源', 'value': 1},
            {'name': '潜江', 'value': 2},
            {'name': '金昌', 'value': 1},
            {'name': '贺州', 'value': 1},
            {'name': '兴安盟', 'value': 1},
            {'name': '安康', 'value': 2},
            {'name': '塔城', 'value': 1},
            {'name': '呼伦贝尔', 'value': 1},
            {'name': '平凉', 'value': 1},
            {'name': '绥化', 'value': 2},
            {'name': '杭州', 'value': 180},
            {'name': '沈阳', 'value': 72},
            {'name': '湛江', 'value': 18},
            {'name': '徐州', 'value': 43},
            {'name': '丽水', 'value': 12},
            {'name': '长春', 'value': 41},
            {'name': '青岛', 'value': 102},
            {'name': '西安', 'value': 157},
            {'name': '桂林', 'value': 16},
            {'name': '呼和浩特', 'value': 14},
            {'name': '合肥', 'value': 83},
            {'name': '广州', 'value': 224},
            {'name': '德阳', 'value': 27},
            {'name': '景德镇', 'value': 4},
            {'name': '泸州', 'value': 12},
            {'name': '淄博', 'value': 25},
            {'name': '南昌', 'value': 48},
            {'name': '深圳', 'value': 178},
            {'name': '汕头', 'value': 28},
            {'name': '常州', 'value': 27},
            {'name': '绵阳', 'value': 31},
            {'name': '厦门', 'value': 49},
            {'name': '潍坊', 'value': 15},
            {'name': '江门', 'value': 19},
            {'name': '宁波', 'value': 35},
            {'name': '宿州', 'value': 6},
            {'name': '金华', 'value': 26},
            {'name': '石河子', 'value': 2},
            {'name': '兰州', 'value': 28},
            {'name': '眉山', 'value': 7},
            {'name': '湘潭', 'value': 12},
            {'name': '玉林', 'value': 11},
            {'name': '鞍山', 'value': 9},
            {'name': '济宁', 'value': 21},
            {'name': '乐山', 'value': 24},
            {'name': '伊春', 'value': 3},
            {'name': '太原', 'value': 40},
            {'name': '湖州', 'value': 12},
            {'name': '宿迁', 'value': 9},
            {'name': '泰州', 'value': 18},
            {'name': '大同', 'value': 9},
            {'name': '四平', 'value': 5},
            {'name': '梧州', 'value': 7},
            {'name': '苏州', 'value': 98},
            {'name': '牡丹江', 'value': 9},
            {'name': '十堰', 'value': 15},
            {'name': '佛山', 'value': 42},
            {'name': '保定', 'value': 29},
            {'name': '镇江', 'value': 23},
            {'name': ' 六安', 'value': 13},
            {'name': '扬州', 'value': 29},
            {'name': '黔西南', 'value': 5},
            {'name': '河池', 'value': 5},
            {'name': '宜昌', 'value': 16},
            {'name': '运城', 'value': 9},
            {'name': '焦作', 'value': 10},
            {'name': '台州', 'value': 33},
            {'name': '延边朝鲜族自治州', 'value': 6},
            {'name': '上饶', 'value': 13},
            {'name': '九江', 'value': 29},
            {'name': '衡阳', 'value': 13},
            {'name': '南阳', 'value': 20},
            {'name': '抚顺', 'value': 7},
            {'name': '大连', 'value': 51},
            {'name': '银川', 'value': 13},
            {'name': '柳州', 'value': 14},
            {'name': '石家庄', 'value': 48},
            {'name': '濮阳', 'value': 3},
            {'name': '怀化', 'value': 5},
            {'name': '益阳', 'value': 8},
            {'name': '赣州', 'value': 20},
            {'name': '包头', 'value': 6},
            {'name': '漳州', 'value': 10},
            {'name': '凉山', 'value': 7},
            {'name': '黔南', 'value': 4},
            {'name': '广安', 'value': 6},
            {'name': '洛阳', 'value': 19},
            {'name': '台北', 'value': 12},
            {'name': '红河', 'value': 3},
            {'name': '大庆', 'value': 6},
            {'name': '韶关', 'value': 19},
            {'name': '芜湖', 'value': 17},
            {'name': '淮北', 'value': 11},
            {'name': '廊坊', 'value': 11},
            {'name': '咸阳', 'value': 13},
            {'name': '自贡', 'value': 14},
            {'name': '温州', 'value': 45},
            {'name': '葫芦岛', 'value': 8},
            {'name': '文山', 'value': 3},
            {'name': '咸宁', 'value': 3},
            {'name': '永州', 'value': 4},
            {'name': '大理', 'value': 10},
            {'name': '潮州', 'value': 6},
            {'name': '泉州', 'value': 40},
            {'name': '平顶山', 'value': 11},
            {'name': '巢湖', 'value': 5},
            {'name': '淮安', 'value': 20},
            {'name': '阜阳', 'value': 20},
            {'name': '新余', 'value': 4},
            {'name': '汉中', 'value': 15},
            {'name': '克拉玛依', 'value': 4},
            {'name': '曲靖', 'value': 5},
            {'name': '日照', 'value': 11},
            {'name': '菏泽', 'value': 16},
            {'name': '保山', 'value': 6},
            {'name': '驻马店', 'value': 13},
            {'name': '赤峰', 'value': 6},
            {'name': '南充', 'value': 17},
            {'name': '双鸭山', 'value': 1},
            {'name': '张家口', 'value': 6},
            {'name': '开封', 'value': 10},
            {'name': '三门峡', 'value': 5},
            {'name': '吉安', 'value': 10},
            {'name': '楚雄', 'value': 4},
            {'name': '锦州', 'value': 7},
            {'name': '阳江', 'value': 6},
            {'name': '高雄', 'value': 5},
            {'name': '百色', 'value': 4},
            {'name': '宜宾', 'value': 12},
            {'name': '岳阳', 'value': 10},
            {'name': '新乡', 'value': 14},
            {'name': '营口', 'value': 2},
            {'name': '白城', 'value': 2},
            {'name': '山南', 'value': 2},
            {'name': '鹤岗', 'value': 2},
            {'name': '巴中', 'value': 6},
            {'name': '昭通', 'value': 2},
            {'name': '黄石', 'value': 5},
            {'name': '南平', 'value': 9},
            {'name': '大兴安岭', 'value': 4},
            {'name': '白银', 'value': 3},
            {'name': '三亚', 'value': 7},
            {'name': '娄底', 'value': 2},
            {'name': '云浮', 'value': 2},
            {'name': '郴州', 'value': 8},
            {'name': '宁德', 'value': 3},
            {'name': '晋城', 'value': 8},
            {'name': '抚州', 'value': 4},
            {'name': '铜仁', 'value': 2},
            {'name': '阳泉', 'value': 5},
            {'name': '盘锦', 'value': 2},
            {'name': '龙岩', 'value': 10},
            {'name': '通化', 'value': 2},
            {'name': '天水', 'value': 5},
            {'name': '阿坝', 'value': 1},
            {'name': '普洱', 'value': 2},
            {'name': '德宏', 'value': 3},
            {'name': '六盘水', 'value': 4},
            {'name': '崇左', 'value': 1},
            {'name': '庆阳', 'value': 1},
            {'name': '仙桃', 'value': 1},
            {'name': '丽江', 'value': 2},
            {'name': '通辽', 'value': 3},
            {'name': '毕节', 'value': 4},
            {'name': '湘西土家族苗族自治州', 'value': 2},
            {'name': '酒泉', 'value': 2},
            {'name': '神农架', 'value': 1},
            {'name': '延安', 'value': 1},
            {'name': '固原', 'value': 2},
            {'name': '台中', 'value': 1}]
    )

    mapOption = {
        animation: true,
        animationDuration: 1000,
        animationEasing: 'cubicInOut',
        animationDurationUpdate: 1000,
        animationEasingUpdate: 'cubicInOut',
        title: {
            text: '热力图',
            subtext: '',
            sublink: 'http://www.pm25.in',
            left: 'center',
            textStyle: {
                color: '#fff'
            }
        },
        backgroundColor: '#051b4a',
        visualMap: [{
            min: 0,
            max: 100,
            splitNumber: 5,
            seriesIndex: 0,
            show: false,
            inRange: {
                color: ['blue', 'blue', 'green', 'yellow', 'red']
            },
            textStyle: {
                color: 'rgb(29,233,182)'
            }
        },{
            min: 0,
            max: 300,
            show: false,
            splitNumber: 5,
            seriesIndex: 1,
            inRange: {
                color: ['#F5B16D', '#F09C42', '#EC870E', '#D0770B']
            },
            textStyle: {
                color: '#fff'
            }
        }],
        geo: {
            map: 'china',
            label: {
                normal: {
                    color: '#389BB7',
                    show: true  //省份名称
                },
                emphasis: {
                    show: false
                }
            },
            roam: true,
            itemStyle: {
                normal: {
                    borderColor: 'rgba(147, 235, 248, 1)',
                    borderWidth: 1,
                    areaColor: {
                        type: 'radial',
                        x: 0.5,
                        y: 0.5,
                        r: 0.8,
                        colorStops: [{
                            offset: 0,
                            color: 'rgba(147, 235, 248, 0)' // 0% 处的颜色
                        }, {
                            offset: 1,
                            color: 'rgba(147, 235, 248, .2)' // 100% 处的颜色
                        }],
                        globalCoord: false // 缺省为 false
                    },
                    shadowColor: 'rgba(128, 217, 248, 1)',
                    // shadowColor: 'rgba(255, 255, 255, 1)',
                    shadowOffsetX: -2,
                    shadowOffsetY: 2,
                    shadowBlur: 10
                },
                emphasis: {
                    color: '#389BB7',
                    areaColor: '#389BB7',
                    borderWidth: 0
                }
            }
        },
        series: [{
            name: 'AQI',
            type: 'heatmap',
            pointSize: 10, // 设置 热力图 点 的大小
            blurSize: 6, // 设置点的 阴影半径
            coordinateSystem: 'geo',
            label: {
                normal: {
                    formatter: '{b}',
                    position: 'right',
                    show: true
                },
                emphasis: {
                    show: true
                }
            },
            itemStyle: {
                normal: {
                    color: '#389BB7'
                }
            },
            roam: true,
            animation: false,
            data: mydata
            // },
            //     {
            //         name: 'AQI',
            //         type: 'heatmap',
            //         pointSize: 6, // 设置 热力图 点 的大小
            //         blurSize: 6, // 设置点的 阴影半径
            //         coordinateSystem: 'geo',
            //         itemStyle: {
            //             normal: {
            //                 color: 'orange'
            //             }
            //         },
            //         data: convertData(baseDataList2)
            //     }]
        }]
    };
    var lineChart = echarts.init(document.getElementById('myChart'));
    lineChart.setOption(mapOption);
});