$(function () {
    var heroChart = echarts.init(document.getElementById('hero'));
    // var xmlFileslug = './hero_graph.gexf';
    // var xmldoc = '';
    // if (window.ActiveXObject)
    //     xmldoc=new ActiveXObject("Microsoft.XMLDOM");
    // else
    // if (document.implementation&&document.implementation.createDocument)
    //     xmldoc=document.implementation.createDocument("","doc",null);
    // console.log(xmldoc);
    // xmldoc.load(xmlFileslug);
    // // var xmlDom = createXMLDom()
    // var graph = echarts.dataTool.gexf.parse(xmldoc);
    // console.log(graph)

    nodes= [{'slug': '暗裔剑魔', 'name': '亚托克斯', 'location': '符文之地'},
            {'slug': '九尾妖狐', 'name': '阿狸', 'location': '艾欧尼亚'},
            {'slug': '离群之刺', 'name': '阿卡丽', 'location': '艾欧尼亚'},
            {'slug': '牛头酋长', 'name': '阿利斯塔', 'location': '符文之地'},
            {'slug': '殇之木乃伊', 'name': '阿木木', 'location': '恕瑞玛'},
            {'slug': '冰晶凤凰', 'name': '艾尼维亚', 'location': '弗雷尔卓德'},
            {'slug': '黑暗之女', 'name': '安妮', 'location': '符文之地'},
            {'slug': '寒冰射手', 'name': '艾希', 'location': '弗雷尔卓德'},
            {'slug': '铸星龙王', 'name': '奥瑞利安·索尔', 'location': '符文之地'},
            {'slug': '沙漠皇帝', 'name': '阿兹尔', 'location': '恕瑞玛'},
            {'slug': '星界游神', 'name': '巴德', 'location': '符文之地'},
            {'slug': '蒸汽机器人', 'name': '布里茨', 'location': '祖安'},
            {'slug': '复仇焰魂', 'name': '布兰德', 'location': '符文之地'},
            {'slug': '弗雷尔卓德之心', 'name': '布隆', 'location': '弗雷尔卓德'},
            {'slug': '皮城女警', 'name': '凯特琳', 'location': '皮尔特沃夫'},
            {'slug': '青钢影', 'name': '卡蜜尔', 'location': '皮尔特沃夫'},
            {'slug': '魔蛇之拥', 'name': '卡西奥佩娅', 'location': '诺克萨斯'},
            {'slug': '虚空恐惧', 'name': '科加斯', 'location': '虚空之地'},
            {'slug': '英勇投弹手', 'name': '库奇', 'location': '班德尔城'},
            {'slug': '诺克萨斯之手', 'name': '德莱厄斯', 'location': '诺克萨斯'},
            {'slug': '皎月女神', 'name': '黛安娜', 'location': '巨神峰'},
            {'slug': '荣耀行刑官', 'name': '德莱文', 'location': '诺克萨斯'},
            {'slug': '祖安狂人', 'name': '蒙多医生', 'location': '祖安'},
            {'slug': '时间刺客', 'name': '艾克', 'location': '祖安'},
            {'slug': '蜘蛛女皇', 'name': '伊莉丝', 'location': '暗影岛'},
            {'slug': '痛苦之拥', 'name': '伊芙琳', 'location': '符文之地'},
            {'slug': '探险家', 'name': '伊泽瑞尔', 'location': '皮尔特沃夫'},
            {'slug': '末日使者', 'name': '费德提克', 'location': '符文之地'},
            {'slug': '无双剑姬', 'name': '菲奥娜', 'location': '德玛西亚'},
            {'slug': '潮汐海灵', 'name': '菲兹', 'location': '符文之地'},
            {'slug': '正义巨像', 'name': '加里奥', 'location': '德玛西亚'},
            {'slug': '海洋之灾', 'name': '普朗克', 'location': '比尔吉沃特'},
            {'slug': '德玛西亚之力', 'name': '盖伦', 'location': '德玛西亚'},
            {'slug': '迷失之牙', 'name': '纳尔', 'location': '弗雷尔卓德'},
            {'slug': '酒桶', 'name': '古拉加斯', 'location': '弗雷尔卓德'},
            {'slug': '法外狂徒', 'name': '格雷福斯', 'location': '比尔吉沃特'},
            {'slug': '战争之影', 'name': '赫卡里姆', 'location': '暗影岛'},
            {'slug': '大发明家', 'name': '黑默丁格', 'location': '皮尔特沃夫'},
            {'slug': '海兽祭司', 'name': '俄洛伊', 'location': '比尔吉沃特'},
            {'slug': '刀锋舞者', 'name': '艾瑞莉娅', 'location': '艾欧尼亚'},
            {'slug': '翠神', 'name': '艾翁', 'location': '艾欧尼亚'},
            {'slug': '风暴之怒', 'name': '迦娜', 'location': '祖安'},
            {'slug': '德玛西亚皇子', 'name': '嘉文四世', 'location': '德玛西亚'},
            {'slug': '武器大师', 'name': '贾克斯', 'location': '符文之地'},
            {'slug': '未来守护者', 'name': '杰斯', 'location': '皮尔特沃夫'},
            {'slug': '戏命师', 'name': '烬', 'location': '艾欧尼亚'},
            {'slug': '暴走萝莉', 'name': '金克丝', 'location': '祖安'},
            {'slug': '虚空之女', 'name': '卡莎', 'location': '虚空之地'},
            {'slug': '复仇之矛', 'name': '卡莉丝塔', 'location': '暗影岛'},
            {'slug': '天启者', 'name': '卡尔玛', 'location': '艾欧尼亚'},
            {'slug': '死亡颂唱者', 'name': '卡尔萨斯', 'location': '暗影岛'},
            {'slug': '虚空行者', 'name': '卡萨丁', 'location': '虚空之地'},
            {'slug': '不祥之刃', 'name': '卡特琳娜', 'location': '诺克萨斯'},
            {'slug': '影流之镰', 'name': '凯隐', 'location': '艾欧尼亚'},
            {'slug': '正义天使', 'name': '正义天使', 'location': '德玛西亚'},
            {'slug': '狂暴之心', 'name': '凯南', 'location': '艾欧尼亚'},
            {'slug': '虚空掠夺者', 'name': '卡兹克', 'location': '虚空之地'},
            {'slug': '永猎双子', 'name': '千珏', 'location': '符文之地'},
            {'slug': '暴怒骑士', 'name': '克烈', 'location': '诺克萨斯'},
            {'slug': '深渊巨口', 'name': '克格莫', 'location': '虚空之地'},
            {'slug': '诡术妖姬', 'name': '乐芙兰', 'location': '诺克萨斯'},
            {'slug': '盲僧', 'name': '李青', 'location': '艾欧尼亚'},
            {'slug': '曙光女神', 'name': '蕾欧娜', 'location': '巨神峰'},
            {'slug': '冰霜女巫', 'name': '丽桑卓', 'location': '弗雷尔卓德'},
            {'slug': '圣枪游侠', 'name': '卢锡安', 'location': '卢恩特拉'},
            {'slug': '仙灵女巫', 'name': '璐璐', 'location': '班德尔城'},
            {'slug': '光辉女郎', 'name': '拉克丝', 'location': '德玛西亚'},
            {'slug': '熔岩巨兽', 'name': '墨菲特', 'location': '以绪塔尔'},
            {'slug': '虚空先知', 'name': '玛尔扎哈', 'location': '虚空之地'},
            {'slug': '扭曲树精', 'name': '茂凯', 'location': '暗影岛'},
            {'slug': '无极剑圣', 'name': '易', 'location': '艾欧尼亚'},
            {'slug': '赏金猎人', 'name': '厄运小姐', 'location': '比尔吉沃特'},
            {'slug': '齐天大圣', 'name': '孙悟空', 'location': '艾欧尼亚'},
            {'slug': '铁铠冥魂', 'name': '莫德凯撒', 'location': '诺克萨斯'},
            {'slug': '堕落天使', 'name': '堕落天使', 'location': '德玛西亚'},
            {'slug': '唤潮鲛姬', 'name': '娜美', 'location': '符文之地'},
            {'slug': '沙漠死神', 'name': '内瑟斯', 'location': '恕瑞玛'},
            {'slug': '深海泰坦', 'name': '诺提勒斯', 'location': '比尔吉沃特'},
            {'slug': '万花通灵', 'name': '妮蔻', 'location': '以绪塔尔'},
            {'slug': '狂野女猎手', 'name': '奈德丽', 'location': '以绪塔尔'},
            {'slug': '永恒梦魇', 'name': '魔腾', 'location': '符文之地'},
            {'slug': '雪原双子', 'name': '努努和威朗普', 'location': '弗雷尔卓德'},
            {'slug': '狂战士', 'name': '奥拉夫', 'location': '弗雷尔卓德'},
            {'slug': '发条魔灵', 'name': '奥莉安娜', 'location': '皮尔特沃夫'},
            {'slug': '山隐之焰', 'name': '奥恩', 'location': '弗雷尔卓德'},
            {'slug': '不屈之枪', 'name': '潘森', 'location': '巨神峰'},
            {'slug': '圣锤之毅', 'name': '波比', 'location': '德玛西亚'},
            {'slug': '血港鬼影', 'name': '派克', 'location': '比尔吉沃特'},
            {'slug': '元素女皇', 'name': '奇亚娜', 'location': '以绪塔尔'},
            {'slug': '德玛西亚之翼', 'name': '奎因', 'location': '德玛西亚'},
            {'slug': '幻翎', 'name': '洛', 'location': '艾欧尼亚'},
            {'slug': '披甲龙龟', 'name': '拉莫斯', 'location': '恕瑞玛'},
            {'slug': '虚空遁地兽', 'name': '雷克塞', 'location': '虚空之地'},
            {'slug': '荒漠屠夫', 'name': '雷克顿', 'location': '恕瑞玛'},
            {'slug': '傲之追猎者', 'name': '雷恩加尔', 'location': '以绪塔尔'},
            {'slug': '放逐之刃', 'name': '锐雯', 'location': '诺克萨斯'},
            {'slug': '机械公敌', 'name': '兰博', 'location': '班德尔城'},
            {'slug': '符文法师', 'name': '瑞兹', 'location': '符文之地'},
            {'slug': '北地之怒', 'name': '瑟庄妮', 'location': '弗雷尔卓德'},
            {'slug': '涤魂圣枪', 'name': '涤魂圣枪', 'location': '卢恩特拉'},
            {'slug': '恶魔小丑', 'name': '萨科', 'location': '符文之地'},
            {'slug': '暮光之眼', 'name': '慎', 'location': '艾欧尼亚'},
            {'slug': '龙血武姬', 'name': '希瓦娜', 'location': '德玛西亚'},
            {'slug': '炼金术士', 'name': '辛吉德', 'location': '祖安'},
            {'slug': '亡灵战神', 'name': '赛恩', 'location': '诺克萨斯'},
            {'slug': '战争女神', 'name': '希维尔', 'location': '恕瑞玛'},
            {'slug': '水晶先锋', 'name': '水晶先锋', 'location': '恕瑞玛'},
            {'slug': '琴瑟仙女', 'name': '娑娜', 'location': '德玛西亚'},
            {'slug': '众星之子', 'name': '索拉卡', 'location': '巨神峰'},
            {'slug': '诺克萨斯统领', 'name': '斯维因', 'location': '诺克萨斯'},
            {'slug': '解脱者', 'name': '塞拉斯', 'location': '德玛西亚'},
            {'slug': '暗黑元首', 'name': '辛德拉', 'location': '艾欧尼亚'},
            {'slug': '河流之王', 'name': '塔姆', 'location': '符文之地'},
            {'slug': '岩雀', 'name': '塔莉垭', 'location': '恕瑞玛'},
            {'slug': '刀锋之影', 'name': '泰隆', 'location': '诺克萨斯'},
            {'slug': '瓦洛兰之盾', 'name': '塔里克', 'location': '巨神峰'},
            {'slug': '迅捷斥候', 'name': '提莫', 'location': '班德尔城'},
            {'slug': '魂锁典狱长', 'name': '锤石', 'location': '暗影岛'},
            {'slug': '麦林炮手', 'name': '崔丝塔娜', 'location': '班德尔城'},
            {'slug': '巨魔之王', 'name': '特朗德尔', 'location': '弗雷尔卓德'},
            {'slug': '蛮族之王', 'name': '泰达米尔', 'location': '弗雷尔卓德'},
            {'slug': '卡牌大师', 'name': '崔斯特', 'location': '比尔吉沃特'},
            {'slug': '瘟疫之源', 'name': '图奇', 'location': '祖安'},
            {'slug': '兽灵行者', 'name': '乌迪尔', 'location': '弗雷尔卓德'},
            {'slug': '无畏战车', 'name': '厄加特', 'location': '祖安'},
            {'slug': '惩戒之箭', 'name': '韦鲁斯', 'location': '艾欧尼亚'},
            {'slug': '暗夜猎手', 'name': '薇恩', 'location': '德玛西亚'},
            {'slug': '邪恶小法师', 'name': '维迦', 'location': '班德尔城'},
            {'slug': '虚空之眼', 'name': '维克兹', 'location': '虚空之地'},
            {'slug': '皮城执法官', 'name': '蔚', 'location': '皮尔特沃夫'},
            {'slug': '机械先驱', 'name': '维克托', 'location': '祖安'},
            {'slug': '猩红收割者', 'name': '弗拉基米尔', 'location': '诺克萨斯'},
            {'slug': '雷霆咆哮', 'name': '沃利贝尔', 'location': '弗雷尔卓德'},
            {'slug': '祖安怒兽', 'name': '沃里克', 'location': '祖安'},
            {'slug': '逆羽', 'name': '霞', 'location': '艾欧尼亚'},
            {'slug': '远古巫灵', 'name': '泽拉斯', 'location': '恕瑞玛'},
            {'slug': '德邦总管', 'name': '赵信', 'location': '德玛西亚'},
            {'slug': '疾风剑豪', 'name': '亚索', 'location': '艾欧尼亚'},
            {'slug': '牧魂人', 'name': '约里克', 'location': '暗影岛'},
            {'slug': '魔法猫咪', 'name': '悠米', 'location': '班德尔城'},
            {'slug': '生化魔人', 'name': '扎克', 'location': '祖安'},
            {'slug': '影流之主', 'name': '劫', 'location': '艾欧尼亚'},
            {'slug': '爆破鬼才', 'name': '吉格斯', 'location': '祖安'},
            {'slug': '时光守护者', 'name': '时光守护者', 'location': '符文之地'},
            {'slug': '暮光星灵', 'name': '佐伊', 'location': '巨神峰'},
            {'slug': '荆棘之兴', 'name': '婕拉', 'location': '以绪塔尔'}];

    links=[{'source': '亚托克斯', 'target': '佐伊', 'weight': 1},
        {'source': '佐伊', 'target': '亚托克斯', 'weight': 1},
        {'source': '阿卡丽', 'target': '凯南', 'weight': 4},
        {'source': '凯南', 'target': '阿卡丽', 'weight': 4},
        {'source': '阿卡丽', 'target': '慎', 'weight': 13},
        {'source': '慎', 'target': '阿卡丽', 'weight': 13},
        {'source': '阿卡丽', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '阿卡丽', 'weight': 2},
        {'source': '阿卡丽', 'target': '劫', 'weight': 3},
        {'source': '劫', 'target': '阿卡丽', 'weight': 3},
        {'source': '阿利斯塔', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '阿利斯塔', 'weight': 1},
        {'source': '艾尼维亚', 'target': '艾希', 'weight': 4},
        {'source': '艾希', 'target': '艾尼维亚', 'weight': 4},
        {'source': '安妮', 'target': '烬', 'weight': 2},
        {'source': '烬', 'target': '安妮', 'weight': 2},
        {'source': '艾希', 'target': '乌迪尔', 'weight': 2},
        {'source': '乌迪尔', 'target': '艾希', 'weight': 2},
        {'source': '艾希', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '艾希', 'weight': 3},
        {'source': '艾希', 'target': '奥恩', 'weight': 1},
        {'source': '奥恩', 'target': '艾希', 'weight': 1},
        {'source': '艾希', 'target': '瑟庄妮', 'weight': 5},
        {'source': '瑟庄妮', 'target': '艾希', 'weight': 5},
        {'source': '艾希', 'target': '泰达米尔', 'weight': 7},
        {'source': '泰达米尔', 'target': '艾希', 'weight': 7},
        {'source': '艾希', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '艾希', 'weight': 2},
        {'source': '阿兹尔', 'target': '内瑟斯', 'weight': 7},
        {'source': '内瑟斯', 'target': '阿兹尔', 'weight': 7},
        {'source': '阿兹尔', 'target': '雷克顿', 'weight': 9},
        {'source': '雷克顿', 'target': '阿兹尔', 'weight': 9},
        {'source': '阿兹尔', 'target': '泽拉斯', 'weight': 67},
        {'source': '泽拉斯', 'target': '阿兹尔', 'weight': 67},
        {'source': '巴德', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '巴德', 'weight': 2},
        {'source': '布里茨', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '布里茨', 'weight': 1},
        {'source': '布里茨', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '布里茨', 'weight': 1},
        {'source': '布里茨', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '布里茨', 'weight': 1},
        {'source': '布兰德', 'target': '瑞兹', 'weight': 6},
        {'source': '瑞兹', 'target': '布兰德', 'weight': 6},
        {'source': '凯特琳', 'target': '蔚', 'weight': 5},
        {'source': '蔚', 'target': '凯特琳', 'weight': 5},
        {'source': '凯特琳', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '凯特琳', 'weight': 2},
        {'source': '卡西奥佩娅', 'target': '卡特琳娜', 'weight': 3},
        {'source': '卡特琳娜', 'target': '卡西奥佩娅', 'weight': 3},
        {'source': '卡西奥佩娅', 'target': '希维尔', 'weight': 8},
        {'source': '希维尔', 'target': '卡西奥佩娅', 'weight': 8},
        {'source': '卡西奥佩娅', 'target': '斯维因', 'weight': 1},
        {'source': '斯维因', 'target': '卡西奥佩娅', 'weight': 1},
        {'source': '卡西奥佩娅', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '卡西奥佩娅', 'weight': 1},
        {'source': '库奇', 'target': '黑默丁格', 'weight': 1},
        {'source': '黑默丁格', 'target': '库奇', 'weight': 1},
        {'source': '库奇', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '库奇', 'weight': 1},
        {'source': '德莱厄斯', 'target': '德莱文', 'weight': 3},
        {'source': '德莱文', 'target': '德莱厄斯', 'weight': 3},
        {'source': '德莱厄斯', 'target': '斯维因', 'weight': 8},
        {'source': '斯维因', 'target': '德莱厄斯', 'weight': 8},
        {'source': '黛安娜', 'target': '蕾欧娜', 'weight': 15},
        {'source': '蕾欧娜', 'target': '黛安娜', 'weight': 15},
        {'source': '伊莉丝', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '伊莉丝', 'weight': 2},
        {'source': '伊芙琳', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '伊芙琳', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '伊泽瑞尔', 'weight': 2},
        {'source': '菲奥娜', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '菲奥娜', 'weight': 1},
        {'source': '菲奥娜', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '菲奥娜', 'weight': 1},
        {'source': '加里奥', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '加里奥', 'weight': 2},
        {'source': '普朗克', 'target': '厄运小姐', 'weight': 14},
        {'source': '厄运小姐', 'target': '普朗克', 'weight': 14},
        {'source': '普朗克', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '普朗克', 'weight': 1},
        {'source': '普朗克', 'target': '斯维因', 'weight': 1},
        {'source': '斯维因', 'target': '普朗克', 'weight': 1},
        {'source': '普朗克', 'target': '劫', 'weight': 3},
        {'source': '劫', 'target': '普朗克', 'weight': 3},
        {'source': '盖伦', 'target': '嘉文四世', 'weight': 6},
        {'source': '嘉文四世', 'target': '盖伦', 'weight': 6},
        {'source': '盖伦', 'target': '烬', 'weight': 2},
        {'source': '烬', 'target': '盖伦', 'weight': 2},
        {'source': '盖伦', 'target': '拉克丝', 'weight': 13},
        {'source': '拉克丝', 'target': '盖伦', 'weight': 13},
        {'source': '古拉加斯', 'target': '艾希', 'weight': 3},
        {'source': '艾希', 'target': '古拉加斯', 'weight': 3},
        {'source': '格雷福斯', 'target': '普朗克', 'weight': 1},
        {'source': '普朗克', 'target': '格雷福斯', 'weight': 1},
        {'source': '格雷福斯', 'target': '崔斯特', 'weight': 9},
        {'source': '崔斯特', 'target': '格雷福斯', 'weight': 9},
        {'source': '格雷福斯', 'target': '劫', 'weight': 4},
        {'source': '劫', 'target': '格雷福斯', 'weight': 4},
        {'source': '赫卡里姆', 'target': '卡莉丝塔', 'weight': 14},
        {'source': '卡莉丝塔', 'target': '赫卡里姆', 'weight': 14},
        {'source': '赫卡里姆', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '赫卡里姆', 'weight': 2},
        {'source': '俄洛伊', 'target': '洛', 'weight': 20},
        {'source': '洛', 'target': '俄洛伊', 'weight': 20},
        {'source': '艾瑞莉娅', 'target': '卡尔玛', 'weight': 2},
        {'source': '卡尔玛', 'target': '艾瑞莉娅', 'weight': 2},
        {'source': '艾瑞莉娅', 'target': '斯维因', 'weight': 2},
        {'source': '斯维因', 'target': '艾瑞莉娅', 'weight': 2},
        {'source': '艾翁', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '艾翁', 'weight': 1},
        {'source': '迦娜', 'target': '易', 'weight': 4},
        {'source': '易', 'target': '迦娜', 'weight': 4},
        {'source': '迦娜', 'target': '洛', 'weight': 4},
        {'source': '洛', 'target': '迦娜', 'weight': 4},
        {'source': '迦娜', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '迦娜', 'weight': 1},
        {'source': '嘉文四世', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '嘉文四世', 'weight': 1},
        {'source': '嘉文四世', 'target': '希瓦娜', 'weight': 8},
        {'source': '希瓦娜', 'target': '嘉文四世', 'weight': 8},
        {'source': '嘉文四世', 'target': '赵信', 'weight': 1},
        {'source': '赵信', 'target': '嘉文四世', 'weight': 1},
        {'source': '杰斯', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '杰斯', 'weight': 1},
        {'source': '杰斯', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '杰斯', 'weight': 1},
        {'source': '杰斯', 'target': '维克托', 'weight': 52},
        {'source': '维克托', 'target': '杰斯', 'weight': 52},
        {'source': '烬', 'target': '慎', 'weight': 6},
        {'source': '慎', 'target': '烬', 'weight': 6},
        {'source': '烬', 'target': '劫', 'weight': 5},
        {'source': '劫', 'target': '烬', 'weight': 5},
        {'source': '金克丝', 'target': '凯特琳', 'weight': 1},
        {'source': '凯特琳', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '蔚', 'weight': 8},
        {'source': '蔚', 'target': '金克丝', 'weight': 8},
        {'source': '金克丝', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '金克丝', 'weight': 2},
        {'source': '卡莎', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '卡莎', 'weight': 1},
        {'source': '卡尔萨斯', 'target': '千珏', 'weight': 2},
        {'source': '千珏', 'target': '卡尔萨斯', 'weight': 2},
        {'source': '卡尔萨斯', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '卡尔萨斯', 'weight': 2},
        {'source': '卡萨丁', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '卡萨丁', 'weight': 2},
        {'source': '凯隐', 'target': '劫', 'weight': 9},
        {'source': '劫', 'target': '凯隐', 'weight': 9},
        {'source': '凯隐', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '凯隐', 'weight': 2},
        {'source': '凯南', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '凯南', 'weight': 1},
        {'source': '凯南', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '凯南', 'weight': 1},
        {'source': '卡兹克', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '卡兹克', 'weight': 1},
        {'source': '卡兹克', 'target': '雷恩加尔', 'weight': 5},
        {'source': '雷恩加尔', 'target': '卡兹克', 'weight': 5},
        {'source': '克格莫', 'target': '玛尔扎哈', 'weight': 5},
        {'source': '玛尔扎哈', 'target': '克格莫', 'weight': 5},
        {'source': '克格莫', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '克格莫', 'weight': 1},
        {'source': '乐芙兰', 'target': '莫德凯撒', 'weight': 4},
        {'source': '莫德凯撒', 'target': '乐芙兰', 'weight': 4},
        {'source': '乐芙兰', 'target': '斯维因', 'weight': 3},
        {'source': '斯维因', 'target': '乐芙兰', 'weight': 3},
        {'source': '李青', 'target': '乌迪尔', 'weight': 9},
        {'source': '乌迪尔', 'target': '李青', 'weight': 9},
        {'source': '蕾欧娜', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '蕾欧娜', 'weight': 1},
        {'source': '蕾欧娜', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '蕾欧娜', 'weight': 2},
        {'source': '丽桑卓', 'target': '易', 'weight': 4},
        {'source': '易', 'target': '丽桑卓', 'weight': 4},
        {'source': '卢锡安', 'target': '锤石', 'weight': 13},
        {'source': '锤石', 'target': '卢锡安', 'weight': 13},
        {'source': '厄运小姐', 'target': '古拉加斯', 'weight': 2},
        {'source': '古拉加斯', 'target': '厄运小姐', 'weight': 2},
        {'source': '厄运小姐', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '厄运小姐', 'weight': 2},
        {'source': '孙悟空', 'target': '易', 'weight': 24},
        {'source': '易', 'target': '孙悟空', 'weight': 24},
        {'source': '孙悟空', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '孙悟空', 'weight': 1},
        {'source': '堕落天使', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '堕落天使', 'weight': 1},
        {'source': '堕落天使', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '堕落天使', 'weight': 1},
        {'source': '娜美', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '娜美', 'weight': 2},
        {'source': '娜美', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '娜美', 'weight': 1},
        {'source': '内瑟斯', 'target': '阿木木', 'weight': 1},
        {'source': '阿木木', 'target': '内瑟斯', 'weight': 1},
        {'source': '内瑟斯', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '内瑟斯', 'weight': 3},
        {'source': '内瑟斯', 'target': '雷克顿', 'weight': 39},
        {'source': '雷克顿', 'target': '内瑟斯', 'weight': 39},
        {'source': '内瑟斯', 'target': '泽拉斯', 'weight': 20},
        {'source': '泽拉斯', 'target': '内瑟斯', 'weight': 20},
        {'source': '妮蔻', 'target': '奈德丽', 'weight': 5},
        {'source': '奈德丽', 'target': '妮蔻', 'weight': 5},
        {'source': '妮蔻', 'target': '霞', 'weight': 1},
        {'source': '霞', 'target': '妮蔻', 'weight': 1},
        {'source': '奈德丽', 'target': '霞', 'weight': 1},
        {'source': '霞', 'target': '奈德丽', 'weight': 1},
        {'source': '魔腾', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '魔腾', 'weight': 1},
        {'source': '努努和威朗普', 'target': '艾尼维亚', 'weight': 1},
        {'source': '艾尼维亚', 'target': '努努和威朗普', 'weight': 1},
        {'source': '努努和威朗普', 'target': '丽桑卓', 'weight': 4},
        {'source': '丽桑卓', 'target': '努努和威朗普', 'weight': 4},
        {'source': '努努和威朗普', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '努努和威朗普', 'weight': 1},
        {'source': '奥拉夫', 'target': '烬', 'weight': 3},
        {'source': '烬', 'target': '奥拉夫', 'weight': 3},
        {'source': '奥拉夫', 'target': '洛', 'weight': 3},
        {'source': '洛', 'target': '奥拉夫', 'weight': 3},
        {'source': '奥拉夫', 'target': '瑟庄妮', 'weight': 6},
        {'source': '瑟庄妮', 'target': '奥拉夫', 'weight': 6},
        {'source': '奥恩', 'target': '布隆', 'weight': 1},
        {'source': '布隆', 'target': '奥恩', 'weight': 1},
        {'source': '奥恩', 'target': '烬', 'weight': 3},
        {'source': '烬', 'target': '奥恩', 'weight': 3},
        {'source': '奥恩', 'target': '沃利贝尔', 'weight': 2},
        {'source': '沃利贝尔', 'target': '奥恩', 'weight': 2},
        {'source': '潘森', 'target': '亚托克斯', 'weight': 8},
        {'source': '亚托克斯', 'target': '潘森', 'weight': 8},
        {'source': '波比', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '波比', 'weight': 2},
        {'source': '派克', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '派克', 'weight': 2},
        {'source': '奎因', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '奎因', 'weight': 2},
        {'source': '奎因', 'target': '洛', 'weight': 9},
        {'source': '洛', 'target': '奎因', 'weight': 9},
        {'source': '洛', 'target': '霞', 'weight': 16},
        {'source': '霞', 'target': '洛', 'weight': 16},
        {'source': '雷克塞', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '雷克塞', 'weight': 1},
        {'source': '雷克顿', 'target': '希维尔', 'weight': 1},
        {'source': '希维尔', 'target': '雷克顿', 'weight': 1},
        {'source': '雷克顿', 'target': '泽拉斯', 'weight': 24},
        {'source': '泽拉斯', 'target': '雷克顿', 'weight': 24},
        {'source': '锐雯', 'target': '辛吉德', 'weight': 1},
        {'source': '辛吉德', 'target': '锐雯', 'weight': 1},
        {'source': '锐雯', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '锐雯', 'weight': 3},
        {'source': '兰博', 'target': '黑默丁格', 'weight': 3},
        {'source': '黑默丁格', 'target': '兰博', 'weight': 3},
        {'source': '瑞兹', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '瑞兹', 'weight': 1},
        {'source': '瑟庄妮', 'target': '乌迪尔', 'weight': 2},
        {'source': '乌迪尔', 'target': '瑟庄妮', 'weight': 2},
        {'source': '瑟庄妮', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '瑟庄妮', 'weight': 2},
        {'source': '涤魂圣枪', 'target': '卢锡安', 'weight': 11},
        {'source': '卢锡安', 'target': '涤魂圣枪', 'weight': 11},
        {'source': '涤魂圣枪', 'target': '锤石', 'weight': 3},
        {'source': '锤石', 'target': '涤魂圣枪', 'weight': 3},
        {'source': '萨科', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '萨科', 'weight': 2},
        {'source': '慎', 'target': '劫', 'weight': 14},
        {'source': '劫', 'target': '慎', 'weight': 14},
        {'source': '希瓦娜', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '希瓦娜', 'weight': 2},
        {'source': '辛吉德', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '辛吉德', 'weight': 1},
        {'source': '辛吉德', 'target': '沃里克', 'weight': 15},
        {'source': '沃里克', 'target': '辛吉德', 'weight': 15},
        {'source': '赛恩', 'target': '斯维因', 'weight': 1},
        {'source': '斯维因', 'target': '赛恩', 'weight': 1},
        {'source': '希维尔', 'target': '阿兹尔', 'weight': 3},
        {'source': '阿兹尔', 'target': '希维尔', 'weight': 3},
        {'source': '希维尔', 'target': '内瑟斯', 'weight': 1},
        {'source': '内瑟斯', 'target': '希维尔', 'weight': 1},
        {'source': '希维尔', 'target': '洛', 'weight': 4},
        {'source': '洛', 'target': '希维尔', 'weight': 4},
        {'source': '希维尔', 'target': '泽拉斯', 'weight': 2},
        {'source': '泽拉斯', 'target': '希维尔', 'weight': 2},
        {'source': '希维尔', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '希维尔', 'weight': 1},
        {'source': '索拉卡', 'target': '霞', 'weight': 1},
        {'source': '霞', 'target': '索拉卡', 'weight': 1},
        {'source': '塞拉斯', 'target': '拉克丝', 'weight': 5},
        {'source': '拉克丝', 'target': '塞拉斯', 'weight': 5},
        {'source': '辛德拉', 'target': '洛', 'weight': 4},
        {'source': '洛', 'target': '辛德拉', 'weight': 4},
        {'source': '塔姆', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '塔姆', 'weight': 2},
        {'source': '塔姆', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '塔姆', 'weight': 1},
        {'source': '塔莉垭', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '塔莉垭', 'weight': 1},
        {'source': '塔里克', 'target': '盖伦', 'weight': 6},
        {'source': '盖伦', 'target': '塔里克', 'weight': 6},
        {'source': '塔里克', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '塔里克', 'weight': 2},
        {'source': '提莫', 'target': '崔丝塔娜', 'weight': 2},
        {'source': '崔丝塔娜', 'target': '提莫', 'weight': 2},
        {'source': '锤石', 'target': '赫卡里姆', 'weight': 3},
        {'source': '赫卡里姆', 'target': '锤石', 'weight': 3},
        {'source': '崔丝塔娜', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '崔丝塔娜', 'weight': 1},
        {'source': '崔丝塔娜', 'target': '兰博', 'weight': 2},
        {'source': '兰博', 'target': '崔丝塔娜', 'weight': 2},
        {'source': '崔丝塔娜', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '崔丝塔娜', 'weight': 2},
        {'source': '特朗德尔', 'target': '丽桑卓', 'weight': 4},
        {'source': '丽桑卓', 'target': '特朗德尔', 'weight': 4},
        {'source': '崔斯特', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '崔斯特', 'weight': 1},
        {'source': '崔斯特', 'target': '劫', 'weight': 2},
        {'source': '劫', 'target': '崔斯特', 'weight': 2},
        {'source': '乌迪尔', 'target': '丽桑卓', 'weight': 1},
        {'source': '丽桑卓', 'target': '乌迪尔', 'weight': 1},
        {'source': '乌迪尔', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '乌迪尔', 'weight': 2},
        {'source': '厄加特', 'target': '斯维因', 'weight': 1},
        {'source': '斯维因', 'target': '厄加特', 'weight': 1},
        {'source': '韦鲁斯', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '韦鲁斯', 'weight': 1},
        {'source': '韦鲁斯', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '韦鲁斯', 'weight': 1},
        {'source': '薇恩', 'target': '丽桑卓', 'weight': 4},
        {'source': '丽桑卓', 'target': '薇恩', 'weight': 4},
        {'source': '维迦', 'target': '莫德凯撒', 'weight': 4},
        {'source': '莫德凯撒', 'target': '维迦', 'weight': 4},
        {'source': '维迦', 'target': '洛', 'weight': 3},
        {'source': '洛', 'target': '维迦', 'weight': 3},
        {'source': '蔚', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '蔚', 'weight': 3},
        {'source': '蔚', 'target': '劫', 'weight': 4},
        {'source': '劫', 'target': '蔚', 'weight': 4},
        {'source': '维克托', 'target': '布里茨', 'weight': 7},
        {'source': '布里茨', 'target': '维克托', 'weight': 7},
        {'source': '维克托', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '维克托', 'weight': 2},
        {'source': '维克托', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '维克托', 'weight': 1},
        {'source': '弗拉基米尔', 'target': '乐芙兰', 'weight': 1},
        {'source': '乐芙兰', 'target': '弗拉基米尔', 'weight': 1},
        {'source': '弗拉基米尔', 'target': '莫德凯撒', 'weight': 2},
        {'source': '莫德凯撒', 'target': '弗拉基米尔', 'weight': 2},
        {'source': '弗拉基米尔', 'target': '洛', 'weight': 3},
        {'source': '洛', 'target': '弗拉基米尔', 'weight': 3},
        {'source': '弗拉基米尔', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '弗拉基米尔', 'weight': 1},
        {'source': '弗拉基米尔', 'target': '斯维因', 'weight': 2},
        {'source': '斯维因', 'target': '弗拉基米尔', 'weight': 2},
        {'source': '沃利贝尔', 'target': '瑟庄妮', 'weight': 1},
        {'source': '瑟庄妮', 'target': '沃利贝尔', 'weight': 1},
        {'source': '泽拉斯', 'target': '卡西奥佩娅', 'weight': 1},
        {'source': '卡西奥佩娅', 'target': '泽拉斯', 'weight': 1},
        {'source': '泽拉斯', 'target': '烬', 'weight': 2},
        {'source': '烬', 'target': '泽拉斯', 'weight': 2},
        {'source': '泽拉斯', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '泽拉斯', 'weight': 1},
        {'source': '赵信', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '赵信', 'weight': 1},
        {'source': '赵信', 'target': '塞拉斯', 'weight': 1},
        {'source': '塞拉斯', 'target': '赵信', 'weight': 1},
        {'source': '亚索', 'target': '锐雯', 'weight': 3},
        {'source': '锐雯', 'target': '亚索', 'weight': 3},
        {'source': '亚索', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '亚索', 'weight': 1},
        {'source': '亚索', 'target': '塔莉垭', 'weight': 3},
        {'source': '塔莉垭', 'target': '亚索', 'weight': 3},
        {'source': '扎克', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '扎克', 'weight': 1},
        {'source': '吉格斯', 'target': '黑默丁格', 'weight': 2},
        {'source': '黑默丁格', 'target': '吉格斯', 'weight': 2},
        {'source': '吉格斯', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '吉格斯', 'weight': 1},
        {'source': '佐伊', 'target': '奥瑞利安·索尔', 'weight': 2},
        {'source': '奥瑞利安·索尔', 'target': '佐伊', 'weight': 2},
        {'source': '佐伊', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '佐伊', 'weight': 2},
        {'source': '佐伊', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '佐伊', 'weight': 1},
        {'source': '婕拉', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '婕拉', 'weight': 2},
        {'source': '易', 'target': '亚索', 'weight': 2},
        {'source': '亚索', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '洛', 'weight': 8},
        {'source': '洛', 'target': '易', 'weight': 8},
        {'source': '易', 'target': '慎', 'weight': 7},
        {'source': '慎', 'target': '易', 'weight': 7},
        {'source': '洛', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '洛', 'weight': 1},
        {'source': '阿木木', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '阿木木', 'weight': 1},
        {'source': '烬', 'target': '易', 'weight': 8},
        {'source': '易', 'target': '烬', 'weight': 8},
        {'source': '烬', 'target': '莫德凯撒', 'weight': 1},
        {'source': '莫德凯撒', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '洛', 'weight': 2},
        {'source': '洛', 'target': '烬', 'weight': 2},
        {'source': '烬', 'target': '弗拉基米尔', 'weight': 1},
        {'source': '弗拉基米尔', 'target': '烬', 'weight': 1},
        {'source': '易', 'target': '莫德凯撒', 'weight': 1},
        {'source': '莫德凯撒', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '弗拉基米尔', 'weight': 1},
        {'source': '弗拉基米尔', 'target': '易', 'weight': 1},
        {'source': '莫德凯撒', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '莫德凯撒', 'weight': 1},
        {'source': '艾希', 'target': '丽桑卓', 'weight': 1},
        {'source': '丽桑卓', 'target': '艾希', 'weight': 1},
        {'source': '塔莉垭', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '塔莉垭', 'weight': 1},
        {'source': '布隆', 'target': '丽桑卓', 'weight': 2},
        {'source': '丽桑卓', 'target': '布隆', 'weight': 2},
        {'source': '卡蜜尔', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '卡蜜尔', 'weight': 1},
        {'source': '卡西奥佩娅', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '卡西奥佩娅', 'weight': 1},
        {'source': '黛安娜', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '黛安娜', 'weight': 1},
        {'source': '伊芙琳', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '伊芙琳', 'weight': 1},
        {'source': '加里奥', 'target': '盖伦', 'weight': 1},
        {'source': '盖伦', 'target': '加里奥', 'weight': 1},
        {'source': '加里奥', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '加里奥', 'weight': 1},
        {'source': '加里奥', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '加里奥', 'weight': 2},
        {'source': '盖伦', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '盖伦', 'weight': 3},
        {'source': '拉克丝', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '拉克丝', 'weight': 3},
        {'source': '盖伦', 'target': '奥拉夫', 'weight': 1},
        {'source': '奥拉夫', 'target': '盖伦', 'weight': 1},
        {'source': '盖伦', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '盖伦', 'weight': 1},
        {'source': '盖伦', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '盖伦', 'weight': 1},
        {'source': '烬', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '蔚', 'weight': 2},
        {'source': '蔚', 'target': '烬', 'weight': 2},
        {'source': '拉克丝', 'target': '奥拉夫', 'weight': 1},
        {'source': '奥拉夫', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '拉克丝', 'weight': 1},
        {'source': '易', 'target': '奥拉夫', 'weight': 1},
        {'source': '奥拉夫', 'target': '易', 'weight': 1},
        {'source': '奥拉夫', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '奥拉夫', 'weight': 1},
        {'source': '奥拉夫', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '奥拉夫', 'weight': 1},
        {'source': '慎', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '慎', 'weight': 1},
        {'source': '艾尼维亚', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '艾尼维亚', 'weight': 1},
        {'source': '艾尼维亚', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '艾尼维亚', 'weight': 1},
        {'source': '艾尼维亚', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '艾尼维亚', 'weight': 1},
        {'source': '普朗克', 'target': '古拉加斯', 'weight': 1},
        {'source': '古拉加斯', 'target': '普朗克', 'weight': 1},
        {'source': '普朗克', 'target': '俄洛伊', 'weight': 1},
        {'source': '俄洛伊', 'target': '普朗克', 'weight': 1},
        {'source': '普朗克', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '普朗克', 'weight': 1},
        {'source': '普朗克', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '普朗克', 'weight': 1},
        {'source': '古拉加斯', 'target': '俄洛伊', 'weight': 1},
        {'source': '俄洛伊', 'target': '古拉加斯', 'weight': 1},
        {'source': '古拉加斯', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '古拉加斯', 'weight': 1},
        {'source': '古拉加斯', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '古拉加斯', 'weight': 1},
        {'source': '古拉加斯', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '古拉加斯', 'weight': 1},
        {'source': '俄洛伊', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '俄洛伊', 'weight': 1},
        {'source': '俄洛伊', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '俄洛伊', 'weight': 1},
        {'source': '俄洛伊', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '俄洛伊', 'weight': 1},
        {'source': '厄运小姐', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '厄运小姐', 'weight': 1},
        {'source': '洛', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '洛', 'weight': 1},
        {'source': '艾瑞莉娅', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '艾瑞莉娅', 'weight': 1},
        {'source': '卡尔玛', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '卡尔玛', 'weight': 1},
        {'source': '易', 'target': '劫', 'weight': 7},
        {'source': '劫', 'target': '易', 'weight': 7},
        {'source': '菲奥娜', 'target': '贾克斯', 'weight': 1},
        {'source': '贾克斯', 'target': '菲奥娜', 'weight': 1},
        {'source': '阿卡丽', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '阿卡丽', 'weight': 1},
        {'source': '烬', 'target': '卡莉丝塔', 'weight': 1},
        {'source': '卡莉丝塔', 'target': '烬', 'weight': 1},
        {'source': '凯隐', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '凯隐', 'weight': 1},
        {'source': '克烈', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '克烈', 'weight': 1},
        {'source': '克烈', 'target': '霞', 'weight': 1},
        {'source': '霞', 'target': '克烈', 'weight': 1},
        {'source': '易', 'target': '霞', 'weight': 1},
        {'source': '霞', 'target': '易', 'weight': 1},
        {'source': '卢锡安', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '卢锡安', 'weight': 2},
        {'source': '阿兹尔', 'target': '墨菲特', 'weight': 1},
        {'source': '墨菲特', 'target': '阿兹尔', 'weight': 1},
        {'source': '阿兹尔', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '阿兹尔', 'weight': 2},
        {'source': '墨菲特', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '墨菲特', 'weight': 1},
        {'source': '易', 'target': '雷克顿', 'weight': 1},
        {'source': '雷克顿', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '泽拉斯', 'weight': 1},
        {'source': '泽拉斯', 'target': '易', 'weight': 1},
        {'source': '内瑟斯', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '内瑟斯', 'weight': 1},
        {'source': '雷克顿', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '雷克顿', 'weight': 1},
        {'source': '泽拉斯', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '泽拉斯', 'weight': 1},
        {'source': '易', 'target': '奈德丽', 'weight': 1},
        {'source': '奈德丽', 'target': '易', 'weight': 1},
        {'source': '奈德丽', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '奈德丽', 'weight': 1},
        {'source': '艾尼维亚', 'target': '布隆', 'weight': 1},
        {'source': '布隆', 'target': '艾尼维亚', 'weight': 1},
        {'source': '艾尼维亚', 'target': '丽桑卓', 'weight': 1},
        {'source': '丽桑卓', 'target': '艾尼维亚', 'weight': 1},
        {'source': '烬', 'target': '沃利贝尔', 'weight': 1},
        {'source': '沃利贝尔', 'target': '烬', 'weight': 1},
        {'source': '奥拉夫', 'target': '奥恩', 'weight': 1},
        {'source': '奥恩', 'target': '奥拉夫', 'weight': 1},
        {'source': '奥拉夫', 'target': '沃利贝尔', 'weight': 1},
        {'source': '沃利贝尔', 'target': '奥拉夫', 'weight': 1},
        {'source': '阿狸', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '阿狸', 'weight': 1},
        {'source': '阿狸', 'target': '迦娜', 'weight': 2},
        {'source': '迦娜', 'target': '阿狸', 'weight': 2},
        {'source': '阿狸', 'target': '金克丝', 'weight': 2},
        {'source': '金克丝', 'target': '阿狸', 'weight': 2},
        {'source': '阿狸', 'target': '璐璐', 'weight': 2},
        {'source': '璐璐', 'target': '阿狸', 'weight': 2},
        {'source': '阿狸', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '阿狸', 'weight': 1},
        {'source': '阿狸', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '阿狸', 'weight': 2},
        {'source': '阿狸', 'target': '波比', 'weight': 2},
        {'source': '波比', 'target': '阿狸', 'weight': 2},
        {'source': '阿狸', 'target': '索拉卡', 'weight': 2},
        {'source': '索拉卡', 'target': '阿狸', 'weight': 2},
        {'source': '伊泽瑞尔', 'target': '迦娜', 'weight': 1},
        {'source': '迦娜', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '潘森', 'weight': 1},
        {'source': '潘森', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '波比', 'weight': 1},
        {'source': '波比', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '索拉卡', 'weight': 1},
        {'source': '索拉卡', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '迦娜', 'target': '金克丝', 'weight': 3},
        {'source': '金克丝', 'target': '迦娜', 'weight': 3},
        {'source': '迦娜', 'target': '璐璐', 'weight': 3},
        {'source': '璐璐', 'target': '迦娜', 'weight': 3},
        {'source': '迦娜', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '迦娜', 'weight': 1},
        {'source': '迦娜', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '迦娜', 'weight': 2},
        {'source': '迦娜', 'target': '波比', 'weight': 3},
        {'source': '波比', 'target': '迦娜', 'weight': 3},
        {'source': '迦娜', 'target': '索拉卡', 'weight': 2},
        {'source': '索拉卡', 'target': '迦娜', 'weight': 2},
        {'source': '金克丝', 'target': '璐璐', 'weight': 3},
        {'source': '璐璐', 'target': '金克丝', 'weight': 3},
        {'source': '金克丝', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '金克丝', 'weight': 2},
        {'source': '金克丝', 'target': '波比', 'weight': 3},
        {'source': '波比', 'target': '金克丝', 'weight': 3},
        {'source': '金克丝', 'target': '索拉卡', 'weight': 2},
        {'source': '索拉卡', 'target': '金克丝', 'weight': 2},
        {'source': '璐璐', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '璐璐', 'weight': 2},
        {'source': '璐璐', 'target': '波比', 'weight': 4},
        {'source': '波比', 'target': '璐璐', 'weight': 4},
        {'source': '璐璐', 'target': '索拉卡', 'weight': 2},
        {'source': '索拉卡', 'target': '璐璐', 'weight': 2},
        {'source': '厄运小姐', 'target': '潘森', 'weight': 1},
        {'source': '潘森', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '波比', 'weight': 1},
        {'source': '波比', 'target': '厄运小姐', 'weight': 1},
        {'source': '厄运小姐', 'target': '索拉卡', 'weight': 1},
        {'source': '索拉卡', 'target': '厄运小姐', 'weight': 1},
        {'source': '潘森', 'target': '波比', 'weight': 2},
        {'source': '波比', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '索拉卡', 'weight': 2},
        {'source': '索拉卡', 'target': '潘森', 'weight': 2},
        {'source': '波比', 'target': '索拉卡', 'weight': 2},
        {'source': '索拉卡', 'target': '波比', 'weight': 2},
        {'source': '烬', 'target': '潘森', 'weight': 2},
        {'source': '潘森', 'target': '烬', 'weight': 2},
        {'source': '易', 'target': '波比', 'weight': 2},
        {'source': '波比', 'target': '易', 'weight': 2},
        {'source': '波比', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '波比', 'weight': 1},
        {'source': '阿狸', 'target': '阿卡丽', 'weight': 1},
        {'source': '阿卡丽', 'target': '阿狸', 'weight': 1},
        {'source': '阿狸', 'target': '伊芙琳', 'weight': 1},
        {'source': '伊芙琳', 'target': '阿狸', 'weight': 1},
        {'source': '阿狸', 'target': '卡莎', 'weight': 1},
        {'source': '卡莎', 'target': '阿狸', 'weight': 1},
        {'source': '阿卡丽', 'target': '伊芙琳', 'weight': 1},
        {'source': '伊芙琳', 'target': '阿卡丽', 'weight': 1},
        {'source': '阿卡丽', 'target': '卡莎', 'weight': 1},
        {'source': '卡莎', 'target': '阿卡丽', 'weight': 1},
        {'source': '伊芙琳', 'target': '卡莎', 'weight': 1},
        {'source': '卡莎', 'target': '伊芙琳', 'weight': 1},
        {'source': '洛', 'target': '拉莫斯', 'weight': 1},
        {'source': '拉莫斯', 'target': '洛', 'weight': 1},
        {'source': '阿兹尔', 'target': '艾克', 'weight': 1},
        {'source': '艾克', 'target': '阿兹尔', 'weight': 1},
        {'source': '阿兹尔', 'target': '雷克塞', 'weight': 1},
        {'source': '雷克塞', 'target': '阿兹尔', 'weight': 1},
        {'source': '艾克', 'target': '雷克塞', 'weight': 1},
        {'source': '雷克塞', 'target': '艾克', 'weight': 1},
        {'source': '易', 'target': '雷恩加尔', 'weight': 1},
        {'source': '雷恩加尔', 'target': '易', 'weight': 1},
        {'source': '赫卡里姆', 'target': '易', 'weight': 2},
        {'source': '易', 'target': '赫卡里姆', 'weight': 2},
        {'source': '卡莉丝塔', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '卡莉丝塔', 'weight': 1},
        {'source': '卡莉丝塔', 'target': '锤石', 'weight': 1},
        {'source': '锤石', 'target': '卡莉丝塔', 'weight': 1},
        {'source': '卡莉丝塔', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '卡莉丝塔', 'weight': 1},
        {'source': '易', 'target': '锤石', 'weight': 2},
        {'source': '锤石', 'target': '易', 'weight': 2},
        {'source': '锤石', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '锤石', 'weight': 1},
        {'source': '烬', 'target': '希瓦娜', 'weight': 1},
        {'source': '希瓦娜', 'target': '烬', 'weight': 1},
        {'source': '艾希', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '艾希', 'weight': 1},
        {'source': '易', 'target': '瑟庄妮', 'weight': 1},
        {'source': '瑟庄妮', 'target': '易', 'weight': 1},
        {'source': '瑟庄妮', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '瑟庄妮', 'weight': 1},
        {'source': '慎', 'target': '乌迪尔', 'weight': 1},
        {'source': '乌迪尔', 'target': '慎', 'weight': 1},
        {'source': '烬', 'target': '索拉卡', 'weight': 1},
        {'source': '索拉卡', 'target': '烬', 'weight': 1},
        {'source': '迦娜', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '迦娜', 'weight': 1},
        {'source': '迦娜', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '迦娜', 'weight': 1},
        {'source': '烬', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '波比', 'weight': 1},
        {'source': '波比', 'target': '烬', 'weight': 1},
        {'source': '璐璐', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '璐璐', 'weight': 1},
        {'source': '波比', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '波比', 'weight': 1},
        {'source': '易', 'target': '斯维因', 'weight': 3},
        {'source': '斯维因', 'target': '易', 'weight': 3},
        {'source': '洛', 'target': '斯维因', 'weight': 3},
        {'source': '斯维因', 'target': '洛', 'weight': 3},
        {'source': '塞拉斯', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '塞拉斯', 'weight': 1},
        {'source': '易', 'target': '沃利贝尔', 'weight': 1},
        {'source': '沃利贝尔', 'target': '易', 'weight': 1},
        {'source': '阿兹尔', 'target': '塔莉垭', 'weight': 1},
        {'source': '塔莉垭', 'target': '阿兹尔', 'weight': 1},
        {'source': '伊泽瑞尔', 'target': '娑娜', 'weight': 1},
        {'source': '娑娜', 'target': '伊泽瑞尔', 'weight': 1},
        {'source': '烬', 'target': '斯维因', 'weight': 1},
        {'source': '斯维因', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '锤石', 'weight': 1},
        {'source': '锤石', 'target': '烬', 'weight': 1},
        {'source': '丽桑卓', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '丽桑卓', 'weight': 1},
        {'source': '嘉文四世', 'target': '凯隐', 'weight': 1},
        {'source': '凯隐', 'target': '嘉文四世', 'weight': 1},
        {'source': '阿狸', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '阿狸', 'weight': 1},
        {'source': '阿狸', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '阿狸', 'weight': 1},
        {'source': '阿狸', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '阿狸', 'weight': 1},
        {'source': '迦娜', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '迦娜', 'weight': 1},
        {'source': '迦娜', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '迦娜', 'weight': 1},
        {'source': '金克丝', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '金克丝', 'weight': 1},
        {'source': '金克丝', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '金克丝', 'weight': 1},
        {'source': '璐璐', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '璐璐', 'weight': 1},
        {'source': '拉克丝', 'target': '潘森', 'weight': 1},
        {'source': '潘森', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '波比', 'weight': 1},
        {'source': '波比', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '索拉卡', 'weight': 1},
        {'source': '索拉卡', 'target': '拉克丝', 'weight': 1},
        {'source': '拉克丝', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '拉克丝', 'weight': 1},
        {'source': '潘森', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '潘森', 'weight': 1},
        {'source': '潘森', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '潘森', 'weight': 1},
        {'source': '波比', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '波比', 'weight': 1},
        {'source': '洛', 'target': '索拉卡', 'weight': 1},
        {'source': '索拉卡', 'target': '洛', 'weight': 1},
        {'source': '索拉卡', 'target': '辛德拉', 'weight': 1},
        {'source': '辛德拉', 'target': '索拉卡', 'weight': 1},
        {'source': '德莱厄斯', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '德莱厄斯', 'weight': 1},
        {'source': '德莱厄斯', 'target': '易', 'weight': 3},
        {'source': '易', 'target': '德莱厄斯', 'weight': 3},
        {'source': '德莱厄斯', 'target': '波比', 'weight': 1},
        {'source': '波比', 'target': '德莱厄斯', 'weight': 1},
        {'source': '德莱厄斯', 'target': '崔丝塔娜', 'weight': 1},
        {'source': '崔丝塔娜', 'target': '德莱厄斯', 'weight': 1},
        {'source': '德莱文', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '德莱文', 'weight': 1},
        {'source': '德莱文', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '德莱文', 'weight': 1},
        {'source': '德莱文', 'target': '波比', 'weight': 1},
        {'source': '波比', 'target': '德莱文', 'weight': 1},
        {'source': '德莱文', 'target': '崔丝塔娜', 'weight': 1},
        {'source': '崔丝塔娜', 'target': '德莱文', 'weight': 1},
        {'source': '璐璐', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '璐璐', 'weight': 1},
        {'source': '璐璐', 'target': '崔丝塔娜', 'weight': 1},
        {'source': '崔丝塔娜', 'target': '璐璐', 'weight': 1},
        {'source': '易', 'target': '崔丝塔娜', 'weight': 2},
        {'source': '崔丝塔娜', 'target': '易', 'weight': 2},
        {'source': '波比', 'target': '崔丝塔娜', 'weight': 1},
        {'source': '崔丝塔娜', 'target': '波比', 'weight': 1},
        {'source': '德莱厄斯', 'target': '洛', 'weight': 1},
        {'source': '洛', 'target': '德莱厄斯', 'weight': 1},
        {'source': '黑默丁格', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '黑默丁格', 'weight': 1},
        {'source': '黑默丁格', 'target': '提莫', 'weight': 1},
        {'source': '提莫', 'target': '黑默丁格', 'weight': 1},
        {'source': '黑默丁格', 'target': '崔丝塔娜', 'weight': 1},
        {'source': '崔丝塔娜', 'target': '黑默丁格', 'weight': 1},
        {'source': '易', 'target': '提莫', 'weight': 1},
        {'source': '提莫', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '塞拉斯', 'weight': 1},
        {'source': '塞拉斯', 'target': '易', 'weight': 1},
        {'source': '阿兹尔', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '阿兹尔', 'weight': 1},
        {'source': '烬', 'target': '内瑟斯', 'weight': 1},
        {'source': '内瑟斯', 'target': '烬', 'weight': 1},
        {'source': '厄运小姐', 'target': '崔斯特', 'weight': 1},
        {'source': '崔斯特', 'target': '厄运小姐', 'weight': 1},
        {'source': '洛', 'target': '图奇', 'weight': 1},
        {'source': '图奇', 'target': '洛', 'weight': 1},
        {'source': '维迦', 'target': '蔚', 'weight': 1},
        {'source': '蔚', 'target': '维迦', 'weight': 1},
        {'source': '易', 'target': '赵信', 'weight': 1},
        {'source': '赵信', 'target': '易', 'weight': 1},
        {'source': '贾克斯', 'target': '慎', 'weight': 1},
        {'source': '慎', 'target': '贾克斯', 'weight': 1},
        {'source': '贾克斯', 'target': '劫', 'weight': 1},
        {'source': '劫', 'target': '贾克斯', 'weight': 1},
        {'source': '德莱厄斯', 'target': '赫卡里姆', 'weight': 1},
        {'source': '赫卡里姆', 'target': '德莱厄斯', 'weight': 1},
        {'source': '德莱厄斯', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '德莱厄斯', 'weight': 1},
        {'source': '赫卡里姆', 'target': '烬', 'weight': 1},
        {'source': '烬', 'target': '赫卡里姆', 'weight': 1},
        {'source': '奥拉夫', 'target': '赵信', 'weight': 1},
        {'source': '赵信', 'target': '奥拉夫', 'weight': 1},
        {'source': '奥瑞利安·索尔', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '奥瑞利安·索尔', 'weight': 1},
        {'source': '奥瑞利安·索尔', 'target': '潘森', 'weight': 1},
        {'source': '潘森', 'target': '奥瑞利安·索尔', 'weight': 1},
        {'source': '易', 'target': '潘森', 'weight': 1},
        {'source': '潘森', 'target': '易', 'weight': 1},
        {'source': '易', 'target': '佐伊', 'weight': 1},
        {'source': '佐伊', 'target': '易', 'weight': 1}];

    var categories = [
        {'name':'以绪塔尔'},
        {'name':'巨神峰'},
        {'name':'弗雷尔卓德'},
        {'name':'德玛西亚'},
        {'name':'恕瑞玛'},
        {'name':'暗影岛'},
        {'name':'诺克萨斯'},
        {'name':'班德尔城'},
        {'name':'皮尔特沃夫'},
        {'name':'祖安'},
        {'name':'虚空之地'},
        {'name':'艾欧尼亚'},
        {'name':'比尔吉沃特'},
        {'name':'符文之地'}
    ];
    // for (var i = 0; i < 9; i++) {
    //     categories[i] = {
    //         slug: '类目' + i
    //     };
    // }
    nodes.forEach(function (node) {
        node.itemStyle = null;
        for(var i=0;i<rank.length;i++){
            if(node.name===rank[i].slug){
                node.symbolSize = 10+rank[i].pagerank*5;
                break;
            }
        }
        // node.value = node.symbolSize;
        // node.symbolSize /= 1.5;
        node.label = {
            normal: {
                fontSize: 15,
                show: true
                // formatter:function () {
                //     var img = '';
                //     for(var i=0;i<imgList.length;i++){
                //         if (node.name === imgList[i].title){
                //             img = imgList[i].img_url
                //         }
                //     }
                //     var dom = "<img style='width:150px;height:300px;' src='http:"+img+"'/>";
                //     return dom
                // }
            }
        };
        node.tooltip = {
            formatter:function () {
                var img = '';
                for(var i=0;i<imgList.length;i++){
                    if (node.name === imgList[i].title){
                        img = imgList[i].img_url;
                        break;
                    }
                }
                var dom = "<img style='width:500px;height:300px;' src='http:"+img+"'/>";
                return dom
            }
        }
        for(var i=0;i<categories.length;i++){
            if (categories[i].name === node.location){
                node.category = i
            }
        }
        // node.location = node.attributes.modularity_class;
        node.x = node.y = null;
        node.draggable = true;
    });
    console.log(nodes);
    heroOption = {
        tooltip: {
            // formatter:function(params){
            //     console.log(params);
            //     var img = '';
            //     for(var i=0;i<imgList.length;i++){
            //         if (params.data.source === imgList[i].title){
            //             img = imgList[i].img_url
            //         }
            //     }
            //     var dom = "<img style='width:150px;height:300px;' src='http:"+img+"'/>";
            //     return dom
            // }
        },
        legend: [{
            // selectedMode: 'single',
            x: 'left',
            data: categories.map(function (a) {
                return a.name;
            })
        }],
        animationDuration: 1500,
        animationEasingUpdate: 'quinticInOut',
        series : [
        {
            name: 'Les Miserables',
            type: 'graph',
            layout: 'force',
            force:{
                repulsion: 700,
                edgeLength: 50,
                gravity: 0.2
            },
            data: nodes,
            links: links,
            categories: categories,
            roam: true,
            focusNodeAdjacency: true,
            itemStyle: {
                normal: {
                    borderColor: '#fff',
                    borderWidth: 1,
                    shadowBlur: 10,
                    shadowColor: 'rgba(0, 0, 0, 0.3)'
                }
            },
            label: {
                position: 'right',
                formatter: '{b}'
            },
            lineStyle: {
                color: 'source',
                curveness: 0.3
            },
            emphasis: {
                lineStyle: {
                    width: 10
                }
            }
        }
    ]
    };
    heroChart.setOption(heroOption);
    heroChart.on('click',function (params) {
        console.log(params);
        var name = '';
        for(var i=0; i<imgList.length;i++){
            if (params.data.name === imgList[i].title){
                name = imgList[i].slug;
                break;
            }
        }
        var base = 'https://yz.lol.qq.com/zh_CN/story/champion/';
        window.open(base+name,'_blank')
    })
});